# -*- coding: utf-8 -*-
"""research_aggregator_group3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lk4b8nxBIwylxy1JBXwmG_MjKEUP3ugd

# 📡 Research Aggregator — 파이프라인 노트북

이 노트북은 **Research Aggregator**의 AI 파이프라인을 단계별로 살펴보는 교육용 노트북입니다.

각 셀이 파이프라인의 한 단계를 담당합니다:

| 셀 | 역할 |
|----|------|
| 셀 1 | 패키지 설치 |
| 셀 2 | 스크래퍼 — Scholar / X / Threads에서 데이터 수집 |
| 셀 3 | 의미론적 랭킹 — 검색어와 가장 관련 있는 결과를 상위로 정렬 |
| 셀 4 | 신뢰도 평가 — 각 결과에 🟢🟡🔴 등급 부여 |
| 셀 5 | 중복 제거 — 여러 플랫폼에 걸친 중복 결과 제거 |
| 셀 6 | 초록 요약 — 긴 Scholar 초록을 짧게 압축 |
| 셀 7 | 캐시 — 검색 기록 저장 및 의미론적 쿼리 매칭 |
| 셀 8 | 🚀 실행 — 주제를 입력하고 전체 파이프라인 실행 |

셀을 위에서부터 순서대로 실행하세요.

## 셀 1 — 패키지 설치

파이프라인에 필요한 라이브러리를 설치합니다.

| 패키지 | 용도 |
|--------|------|
| `sentence-transformers` | 텍스트를 벡터로 변환 (랭킹, 캐시 쿼리 매칭) |
| `transformers` | Hugging Face AI 모델 실행 환경 (초록 요약) |
| `torch` | PyTorch — 위 두 라이브러리의 딥러닝 엔진 |
| `scholarly` | Google Scholar 스크래퍼 |
| `ntscraper` | X(트위터) 스크래퍼 (API 키 불필요) |
| `httpx` | 비동기 HTTP 클라이언트 (Threads 스크래핑) |
| `numpy` | 벡터 간 코사인 유사도 계산 |
| `accelerate` | 모델 학습/추론 속도 최적화 |
| `rank-bm25` | BM25 점수(배치 내)로 dense 임베딩과 결합 |
"""

import subprocess, sys

packages = [
    "sentence-transformers",
    "transformers",
    "torch",
    "scholarly",
    "free-proxy",   # used by scholarly's FreeProxies() to bypass Google Scholar blocking
    "httpx",
    "numpy",
    "accelerate",
    "nest_asyncio",
    "rank-bm25",    # lexical scores fused with dense embeddings (RRF / weighted)
]

print("📦 패키지 설치 중...")
subprocess.run([sys.executable, "-m", "pip", "install", "-q"] + packages, check=True)
print("✅ 설치 완료!")

"""## 셀 1b — Serper API 키 설정

X와 Threads 검색, 그리고 scholarly 실패 시 Scholar 대체 검색에
**Serper.dev** Google Search API를 사용합니다.

**무료 키 발급 (2,500건/월):**
1. [serper.dev](https://serper.dev) 에서 무료 가입
2. 대시보드에서 API 키 복사
3. 아래 셀의 `PASTE_YOUR_NEW_KEY_HERE` 자리에 붙여넣기

> ⚠️ API 키를 다른 사람과 공유하지 마세요. 유출됐다면 serper.dev에서 즉시 재발급하세요.

"""

import os

# ⚠️  Paste your NEW Serper API key here after regenerating it at serper.dev
# Never share this key publicly — regenerate it if you do.
# Get a free key (2,500 searches/month) at: https://serper.dev

# Never commit real keys. Set in Colab: os.environ["SERPER_API_KEY"] = "your_key"
# Or use Colab secrets / local env before running this cell.
SERPER_API_KEY = os.environ.get("SERPER_API_KEY", "")
os.environ["SERPER_API_KEY"] = SERPER_API_KEY
if SERPER_API_KEY:
    print(f"✅ Serper API 키 설정 완료 ({SERPER_API_KEY[:6]}...{SERPER_API_KEY[-4:]})")
else:
    print("⚠️  SERPER_API_KEY 없음 — https://serper.dev 에서 발급 후 이 셀 위에서 os.environ에 설정하세요.")

"""## 셀 2 — 스크래퍼 (Scraper)

세 플랫폼에서 데이터를 가져오는 함수들을 정의합니다.

### 왜 Serper.dev인가?

Google은 Colab 같은 클라우드 서버 IP를 차단합니다. Serper는 Google 검색 결과를
파싱 없이 깨끗한 JSON으로 돌려주는 API입니다.

### X / Threads — 논문 링크 추출 방식

단순히 게시물 URL을 가져오는 게 아닙니다. 각 게시물 안에 있는
**논문/저널 링크**를 추출하고, 링크가 없는 게시물은 버립니다.

```
Serper 검색 → 게시물 URL + snippet
    ↓
1. snippet에서 academic URL 패턴 매칭
   (arxiv, doi, nature, pubmed, sciencedirect 등)
    ↓
2. snippet에 t.co 단축링크가 있으면 실제 URL로 해제
    ↓
3. 그래도 없으면 게시물 페이지 직접 fetch → HTML에서 추출
    ↓
논문 링크 있는 게시물만 유지 → post_url + paper_url 둘 다 반환
```

결과에는 `url` (게시물 링크)과 `paper_url` (논문/저널 링크) 두 개가 모두 포함됩니다.

### Scholar
scholarly 라이브러리로 먼저 시도하고, 실패 시 Serper로 자동 대체합니다.

"""

import asyncio
import httpx
import logging
import os
import re
from datetime import datetime, timedelta
from typing import Optional
from urllib.parse import unquote

try:
    import nest_asyncio
    nest_asyncio.apply()
except ImportError:
    pass

logging.basicConfig(level=logging.ERROR)

SERPER_API_KEY = os.environ.get("SERPER_API_KEY", "")

# ── Academic URL patterns ─────────────────────────────────────────────────────
# Matches links to journals, preprints, DOIs, and academic publishers.
# Used to find the paper link embedded inside an X or Threads post.

ACADEMIC_DOMAINS = re.compile(
    r'https?://(?:www\.)?' + r'(?:' + '|'.join(re.escape(d) for d in [
        "arxiv.org", "biorxiv.org", "medrxiv.org", "ssrn.com",
        "doi.org", "dx.doi.org",
        "nature.com", "science.org", "cell.com", "thelancet.com",
        "nejm.org", "bmj.com", "pnas.org", "plos.org",
        "pubmed.ncbi.nlm.nih.gov", "ncbi.nlm.nih.gov",
        "sciencedirect.com", "springer.com", "springerlink.com",
        "onlinelibrary.wiley.com", "wiley.com",
        "jstor.org", "tandfonline.com", "sagepub.com",
        "academic.oup.com", "oxfordacademic.com",
        "cambridge.org", "royalsocietypublishing.org",
        "frontiersin.org", "mdpi.com", "hindawi.com",
        "ieeexplore.ieee.org", "dl.acm.org", "openreview.net",
        "proceedings.mlr.press", "jmlr.org", "aaai.org",
        "jamanetwork.com", "ahajournals.org",
        "researchgate.net", "semanticscholar.org",
        "zenodo.org", "osf.io", "figshare.com",
    ]) + r')' + r'[^\s"\'<>)\]]*',
    re.IGNORECASE,
)

# Also catch t.co shortlinks that commonly wrap paper URLs in tweets
TCO_PATTERN = re.compile(r'https?://t\.co/[A-Za-z0-9]+')


def extract_academic_url(text: str) -> Optional[str]:
    """Return the first academic/journal URL found in a block of text, or None."""
    m = ACADEMIC_DOMAINS.search(text)
    return m.group(0).rstrip(".,;)") if m else None


async def resolve_tco(shorturl: str, client: httpx.AsyncClient) -> Optional[str]:
    """Follow a t.co shortlink and return the final URL."""
    try:
        resp = await client.head(shorturl, follow_redirects=True, timeout=4.0)
        final = str(resp.url)
        if ACADEMIC_DOMAINS.match(final):
            return final
        return None
    except Exception:
        return None


async def fetch_page_links(url: str, client: httpx.AsyncClient) -> Optional[str]:
    """
    Fetch a post page and scan its HTML for academic links.
    Works well for Threads (public HTML). X often requires login,
    but sometimes the meta tags or og:description still contain the URL.
    """
    try:
        resp = await client.get(url, follow_redirects=True, timeout=6.0)
        html = resp.text

        # Check meta description / og:description first (fastest)
        for m in re.finditer(r'content="([^"]{20,})"', html):
            found = extract_academic_url(m.group(1))
            if found:
                return found

        # Full HTML scan
        found = extract_academic_url(html)
        if found:
            return found

        # Try resolving any t.co links found on the page
        for tco in TCO_PATTERN.findall(html)[:5]:
            resolved = await resolve_tco(tco, client)
            if resolved:
                return resolved

        return None
    except Exception:
        return None


async def enrich_with_paper_url(
    post_url: str,
    snippet: str,
    client: httpx.AsyncClient,
) -> Optional[str]:
    """
    Find the academic paper URL referenced by a post.
    1. Check the Serper snippet (Google often indexes tweet text incl. URLs)
    2. Resolve any t.co shortlinks in the snippet
    3. Fetch the actual post page as a last resort
    """
    # 1. Snippet scan
    found = extract_academic_url(snippet)
    if found:
        return found

    # 2. Resolve t.co links from snippet
    for tco in TCO_PATTERN.findall(snippet)[:3]:
        resolved = await resolve_tco(tco, client)
        if resolved:
            return resolved

    # 3. Fetch post page
    found = await fetch_page_links(post_url, client)
    return found


# ── Date filter ───────────────────────────────────────────────────────────────

def _days_to_tbs(days: Optional[int]) -> Optional[str]:
    """
    Direct mapping to Serper's supported tbs values.
    Sentinel values from parse_date_input:
      0   → past hour  → qdr:h
      1   → past day   → qdr:d
      7   → past week  → qdr:w
      30  → past month → qdr:m
      365 → past year  → qdr:y
      None → all time  → no tbs
    """
    if days is None: return None
    if days == 0:    return "qdr:h"
    if days == 1:    return "qdr:d"
    if days == 7:    return "qdr:w"
    if days == 30:   return "qdr:m"
    if days == 365:  return "qdr:y"
    return None


def _cutoff_year(days: Optional[int]) -> Optional[int]:
    """Return the earliest acceptable publication year for a days filter.
    Treats 0 (past hour) as today's year."""
    if days is None: return None
    if days == 0:    return datetime.now().year
    return (datetime.now() - timedelta(days=days)).year


def _year_range_str(days: Optional[int]) -> str:
    """
    Injects a year into Scholar queries as a workaround since /scholar
    ignores tbs. Scholar can only filter to year granularity — there is
    no way to express 'past hour' or 'past week' in a Scholar query string.

    Mapping:
      0  (hour)  → current year only  (best we can do; tbs=qdr:h handles the rest)
      1  (day)   → current year only
      7  (week)  → current year only
      30 (month) → current year only
      365 (year) → last year OR current year (e.g. "2025 OR 2026")
      None       → no injection
    """
    if days is None:
        return ""
    now = datetime.now()
    current_year = now.year
    # For sub-year windows, current year is the only meaningful injection
    if days < 365:
        return str(current_year)
    # For a full year, include last year too since "past year" spans two calendar years
    return f"{current_year - 1} OR {current_year}"


def _snippet_in_range(snippet: str, days: Optional[int]) -> bool:
    """
    Heuristic check: does the snippet contain a year within the allowed range?
    Used as a secondary filter for web/social results where tbs isn't perfect.
    Returns True (keep) if no year found in snippet (give benefit of the doubt)
    or if a found year is within range.
    """
    if not days:
        return True
    cutoff = _cutoff_year(days)
    current = datetime.now().year
    years_in_snippet = re.findall(r'\b(20\d{2})\b', snippet)
    if not years_in_snippet:
        return True  # no year mentioned — keep
    return any(cutoff <= int(y) <= current for y in years_in_snippet)


# ── Serper search ─────────────────────────────────────────────────────────────

async def _serper_search(query: str, days: Optional[int], limit: int) -> list:
    if not SERPER_API_KEY:
        print("      [Serper] ❌ SERPER_API_KEY not set")
        return []

    payload = {"q": query, "num": min(limit * 2, 10)}
    tbs = _days_to_tbs(days)
    if tbs:
        payload["tbs"] = tbs
        print(f"      [Serper] tbs={tbs} for query: {query[:60]}")

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(
                "https://google.serper.dev/search",
                json=payload,
                headers={"X-API-KEY": SERPER_API_KEY, "Content-Type": "application/json"},
            )
            if not resp.is_success:
                print(f"      [Serper] ❌ {resp.status_code}: {resp.text[:200]}")
                return []
            data = resp.json()

        results = [{"title":   r.get("title", ""),
                    "url":     r.get("link", ""),
                    "snippet": r.get("snippet", "")}
                   for r in data.get("organic", [])]
        print(f"      [Serper] {len(results)} results for: {query[:70]}")
        return results

    except Exception as e:
        print(f"      [Serper] ❌ {type(e).__name__}: {e}")
        return []


# ── Social post enrichment ────────────────────────────────────────────────────

async def _enrich_social_results(raw: list, domain_filter: str, source: str,
                                  venue: str, author_pattern: str,
                                  limit: int) -> list:
    """
    For each candidate post from Serper:
    - Confirm the URL belongs to the right platform
    - Find the academic paper URL inside the post
    - Discard posts with no paper link
    - Return up to `limit` enriched results
    """
    candidates = [r for r in raw if domain_filter in r["url"]]
    print(f"      [{source}] {len(candidates)} candidates after domain filter")
    if not candidates:
        return []

    # Print every candidate before filtering so we can see what's being evaluated
    for i, c in enumerate(candidates):
        print(f"      [{source}] [{i+1}] {c['url'][:80]}")
        if c["snippet"]:
            print(f"             snippet: {c['snippet'][:100]}")

    async with httpx.AsyncClient(
        timeout=httpx.Timeout(connect=3.0, read=5.0, write=3.0, pool=3.0),
        follow_redirects=True,
        headers={"User-Agent": "Mozilla/5.0 (compatible; ResearchBot/1.0)"},
    ) as client:
        tasks     = [enrich_with_paper_url(r["url"], r["snippet"], client) for r in candidates]
        paper_urls = await asyncio.gather(*tasks, return_exceptions=True)

    results = []
    for item, paper_url in zip(candidates, paper_urls):
        if isinstance(paper_url, Exception) or not paper_url:
            print(f"      [{source}] ✗ no paper link — skipped: {item['url'][:70]}")
            continue

        print(f"      [{source}] ✓ paper found: {paper_url[:80]}")
        m      = re.search(author_pattern, item["url"])
        author = f"@{m.group(1)}" if m else "@unknown"

        results.append({
            "source":           source,
            "title":            item["title"][:80],
            "authors":          author,
            "date":             "recent",
            "snippet":          (item["snippet"] or item["title"])[:400],
            "url":              item["url"],
            "paper_url":        paper_url,
            "citations":        0,
            "venue":            venue,
            "raw_score":        0.0,
            "reliability_score": 0.0,
            "reliability_tier": "uncertain",
            "is_new":           True,
        })

        if len(results) >= limit:
            break

    return results


async def _serper_scholar_search(query: str, days: Optional[int], limit: int) -> list:
    """
    Search via Serper's dedicated Google Scholar endpoint (/scholar).
    The /scholar endpoint does not reliably respect tbs, so we inject
    the year range directly into the query string as a stronger signal.
    """
    if not SERPER_API_KEY:
        return []

    # Inject year(s) into query — far more reliable than tbs for Scholar
    year_str = _year_range_str(days)
    full_query = f"{query} {year_str}".strip() if year_str else query

    payload = {"q": full_query, "num": min(limit * 2, 10)}
    # Still pass tbs as a secondary signal even if Scholar ignores it
    tbs = _days_to_tbs(days)
    if tbs:
        payload["tbs"] = tbs

    if year_str:
        if days is not None and days < 365:
            print(f"      [Serper Scholar] ℹ️  Scholar은 연도 단위 필터만 지원 — {year_str}년 결과로 제한")
        else:
            print(f"      [Serper Scholar] year filter injected: {year_str}")

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(
                "https://google.serper.dev/scholar",
                json=payload,
                headers={"X-API-KEY": SERPER_API_KEY, "Content-Type": "application/json"},
            )
            if not resp.is_success:
                print(f"      [Serper Scholar] ❌ {resp.status_code}: {resp.text[:200]}")
                return []
            data = resp.json()

        results = []
        for r in data.get("organic", [])[:limit]:
            results.append({
                "title":     r.get("title", ""),
                "url":       r.get("link", ""),
                "snippet":   r.get("snippet", ""),
                "authors":   r.get("publicationInfo", ""),
                "year":      str(r.get("year", "")),
                "venue":     r.get("publication", "Google Scholar"),
                "citations": r.get("citedBy", {}).get("total", 0) if isinstance(r.get("citedBy"), dict) else 0,
            })

        print(f"      [Serper Scholar] {len(results)} results for: {full_query[:70]}")
        return results

    except Exception as e:
        print(f"      [Serper Scholar] ❌ {type(e).__name__}: {e}")
        return []


# ── Google Scholar ────────────────────────────────────────────────────────────

async def scrape_scholar(topic: str, days: Optional[int] = None, limit: int = 5) -> list:
    """scholarly 우선 (FreeProxies 사용), 실패 시 Serper로 대체."""
    print("   📚 Google Scholar 검색 중...")
    try:
        from scholarly import scholarly, ProxyGenerator

        def _fetch():
            # Set up FreeProxies so scholarly can rotate through free proxy IPs
            # This bypasses Google's block on Colab's datacenter IP.
            pg = ProxyGenerator()
            success = pg.FreeProxies()
            if success:
                scholarly.use_proxy(pg)
                print("      [scholarly] ✅ FreeProxies 프록시 설정 완료")
            else:
                print("      [scholarly] ⚠️  FreeProxies 설정 실패 — 직접 연결 시도...")

            results, gen = [], scholarly.search_pubs(topic)
            for _ in range(limit):
                try:
                    pub  = next(gen)
                    bib  = pub.get("bib", {})
                    year = str(bib.get("pub_year", ""))
                    if days and year:
                        try:
                            if int(year) < (datetime.now() - timedelta(days=days)).year:
                                continue
                        except ValueError:
                            pass
                    results.append({
                        "source":    "scholar",
                        "title":     bib.get("title", "Untitled"),
                        "authors":   ", ".join(bib.get("author", [])[:3]),
                        "date":      year,
                        "snippet":   bib.get("abstract", "")[:400],
                        "url":       pub.get("pub_url") or f"https://scholar.google.com/scholar?q={topic.replace(' ','+')}",
                        "paper_url": pub.get("pub_url", ""),
                        "citations": pub.get("num_citations", 0),
                        "venue":     bib.get("venue", ""),
                        "raw_score": 0.0, "reliability_score": 0.0,
                        "reliability_tier": "uncertain", "is_new": True,
                    })
                except StopIteration:
                    break
            return results

        loop    = asyncio.get_event_loop()
        results = await asyncio.wait_for(loop.run_in_executor(None, _fetch), timeout=30.0)
        if results:
            print(f"   ✅ Scholar (scholarly) 완료: {len(results)}건")
            return results
        print("   ⚠️  scholarly 결과 없음 — Serper로 대체...")

    except asyncio.TimeoutError:
        print("   ⏱️  scholarly 시간 초과 (30s) — Google이 Colab IP를 일시 차단 중일 수 있습니다. Serper로 대체...")
    except Exception as e:
        # MaxTriesExceeded = Google blocked scholarly's scrape attempts
        # Typically happens because Colab's IP is flagged by Google
        print(f"   ⚠️  scholarly 실패: {type(e).__name__}: {e}")
        print(f"   → 이는 보통 Google이 Colab IP를 차단했을 때 발생합니다. Serper로 대체...")

    try:
        raw     = await _serper_scholar_search(topic, days, limit)
        results = []

        # Compute cutoff year from days filter so we can enforce it ourselves —
        # Serper's Scholar endpoint doesn't reliably honour the tbs date param.
        cutoff_year = None
        if days:
            from datetime import datetime, timedelta
            cutoff_year = (datetime.now() - timedelta(days=days)).year

        for r in raw:
            if not r["url"]:
                continue
            # Drop papers older than the requested date range
            if cutoff_year and r.get("year"):
                try:
                    if int(r["year"]) < cutoff_year:
                        continue
                except ValueError:
                    pass
            results.append({
                "source":    "scholar",
                "title":     r["title"][:200],
                "authors":   r.get("authors", ""),
                "date":      r.get("year", ""),
                "snippet":   r["snippet"][:400],
                "url":       r["url"],
                "paper_url": r["url"],
                "citations": r.get("citations", 0),
                "venue":     r.get("venue", "Google Scholar"),
                "raw_score": 0.0, "reliability_score": 0.0,
                "reliability_tier": "uncertain", "is_new": True,
            })
        print(f"   ✅ Scholar (Serper 대체) 완료: {len(results)}건"
              + (f"  (cutoff: {cutoff_year}년 이후)" if cutoff_year else ""))
        return results
    except Exception as e:
        print(f"   ❌ Scholar 완전 실패: {e}")
        return []


# ── X / Twitter ───────────────────────────────────────────────────────────────

async def scrape_x(topic: str, days: Optional[int] = None, limit: int = 5) -> list:
    """
    Serper로 X 게시물을 찾고, 각 게시물 안의 논문/저널 링크를 추출합니다.
    논문 링크가 없는 게시물은 제외합니다.
    """
    print("   🐦 X (site:x.com) 검색 중...")
    raw = await _serper_search(
        f'site:x.com {topic} paper OR arxiv OR doi',
        days, limit * 2,
    )
    print(f"   🔍 X 후보 {len(raw)}건 — 논문 링크 추출 중...")
    results = await _enrich_social_results(
        raw, "x.com", "x", "X / Twitter", r'x\.com/([^/?]+)', limit
    )
    print(f"   ✅ X 완료: {len(results)}건 (논문 링크 포함 게시물만)")
    return results


# ── Threads ───────────────────────────────────────────────────────────────────

async def scrape_threads(topic: str, days: Optional[int] = None, limit: int = 5) -> list:
    """
    Serper로 Threads 게시물을 찾고, 각 게시물 안의 논문/저널 링크를 추출합니다.
    논문 링크가 없는 게시물은 제외합니다.
    """
    print("   🧵 Threads 검색 중...")
    raw_net, raw_com = await asyncio.gather(
        _serper_search(f'site:threads.net {topic} paper OR arxiv OR doi', days, limit * 2),
        _serper_search(f'site:threads.com {topic} paper OR arxiv OR doi', days, limit * 2),
    )
    print(f"   🔍 Threads 후보 — net:{len(raw_net)}건, com:{len(raw_com)}건 — 논문 링크 추출 중...")

    # Combine and deduplicate by URL before enrichment
    seen, combined = set(), []
    for item in raw_net + raw_com:
        if item["url"] not in seen:
            seen.add(item["url"])
            combined.append(item)

    results = await _enrich_social_results(
        combined, "threads", "threads", "Threads",
        r'threads\.[a-z]+/@?([^/?]+)', limit
    )
    print(f"   ✅ Threads 완료: {len(results)}건 (논문 링크 포함 게시물만)")
    return results


# ── Generic Google search ─────────────────────────────────────────────────────

async def scrape_web(topic: str, days: Optional[int] = None, limit: int = 5) -> list:
    """
    Generic Google search via Serper — no site: filter.
    Catches anything the other three sources miss: blog posts, news articles,
    university pages, preprint servers, etc.
    Excludes results already covered by Scholar, X, and Threads.
    """
    print("   🌐 웹 전체 검색 중...")
    _EXCLUDE = ("x.com", "twitter.com", "threads.net", "threads.com",
                "scholar.google.com")
    try:
        raw = await _serper_search(f'{topic} research paper OR study OR findings', days, limit * 2)
        results = []
        for item in raw:
            url = item["url"]
            if any(d in url for d in _EXCLUDE):
                continue
            # Secondary date filter: check snippet for year mentions
            if not _snippet_in_range(item["snippet"] + " " + item["title"], days):
                print(f"      [web] ✗ date out of range — skipped: {url[:60]}")
                continue
            results.append({
                "source":           "web",
                "title":            item["title"][:200],
                "authors":          "",
                "date":             "",
                "snippet":          item["snippet"][:400],
                "url":              url,
                "paper_url":        "",
                "citations":        0,
                "venue":            "Web",
                "raw_score":        0.0,
                "reliability_score": 0.0,
                "reliability_tier": "uncertain",
                "is_new":           True,
            })
            if len(results) >= limit:
                break
        print(f"   ✅ 웹 완료: {len(results)}건")
        return results
    except Exception as e:
        print(f"   ❌ 웹 검색 실패: {e}")
        return []


# ── Orchestrator ──────────────────────────────────────────────────────────────

async def scrape_all(topic: str, days: Optional[int] = None) -> dict:
    scholar, x, threads, web = await asyncio.gather(
        scrape_scholar(topic, days),
        scrape_x(topic, days),
        scrape_threads(topic, days),
        scrape_web(topic, days),
    )
    return {"scholar": scholar, "x": x, "threads": threads, "web": web}


print("✅ 스크래퍼 정의 완료")
print("   Scholar : scholarly → Serper 대체")
print("   X       : Serper + 논문 링크 추출")
print("   Threads : Serper + 논문 링크 추출")
print("   Web     : Serper 전체 웹 검색")

"""## 셀 3 — 의미론적 랭킹 (Semantic Ranker)

스크래핑된 결과를 **검색 주제와의 관련성** 순서대로 정렬합니다.

### 핵심 개념: 텍스트 임베딩

텍스트를 숫자 벡터로 변환하면 "의미가 얼마나 비슷한지"를 수학적으로 측정할 수 있습니다.

```
"LLM alignment"  →  [0.82, 0.11, 0.45, ...]  384차원 벡터
"AI safety"      →  [0.79, 0.13, 0.47, ...]  (비슷한 방향 → 높은 유사도)
"고양이 사료"     →  [0.02, 0.91, 0.03, ...]  (다른 방향 → 낮은 유사도)
```

두 벡터가 같은 방향을 가리키는 정도를 **코사인 유사도**로 측정합니다. 1.0이면 완전 동일, 0이면 무관합니다.

### Ranker (English)
- **Bi-encoder:** `BAAI/bge-base-en-v1.5` (query prefix per model card; passages unprefixed).
- **Lexical:** BM25 (`rank-bm25`) on the result batch + a light English keyword score.
- **Fusion:** `RANK_MERGE_MODE` — `rrf` (reciprocal rank fusion) or `weighted_norm` (min–max then weighted sum).
- **Optional:** top-`K` **cross-encoder** rerank (`ms-marco-MiniLM-L-6-v2`) on the fused list.
- **Fallback:** keyword-only if models fail.

"""

import numpy as np

# --- Bi-encoder (BGE English; GTE alternative e.g. Alibaba-NLP/gte-base-en-v1.5 in README) ---
_RANK_BI_ENCODER = None
RANK_BI_ENCODER_MODEL_NAME = "BAAI/bge-base-en-v1.5"
BGE_QUERY_PREFIX = "Represent this sentence for searching relevant passages: "

# rrf: fuse dense / BM25 / keyword rank lists. weighted_norm: min-max normalize each score vector.
RANK_MERGE_MODE = "rrf"  # "rrf" | "weighted_norm"
RRF_K = 60

_WEIGHTED_NORM_DENSE = 0.55
_WEIGHTED_NORM_BM25 = 0.35
_WEIGHTED_NORM_KEYWORD = 0.10

_CROSS_ENCODER = None
RANK_CROSS_ENCODER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"
RANK_CROSS_ENCODER_TOP_K = 40
_CROSS_ENCODER_BLEND = 0.55

_RANK_KEYWORD_STOPWORDS = frozenset({
    "the", "a", "an", "and", "or", "but", "if", "then", "else", "when", "where",
    "in", "on", "at", "to", "for", "of", "with", "by", "from", "as", "into",
    "is", "was", "are", "were", "been", "be", "being", "am",
    "have", "has", "had", "having", "do", "does", "did", "doing",
    "will", "would", "could", "should", "may", "might", "must", "shall", "can",
    "not", "no", "nor", "only", "own", "same", "so", "than", "too", "very",
    "just", "also", "both", "each", "few", "more", "most", "other", "some", "such",
    "this", "that", "these", "those", "here", "there", "what", "which", "who", "whom",
    "whose", "why", "how", "all", "any", "every", "about", "above", "after", "again",
    "against", "before", "below", "between", "through", "during", "without", "within",
})


def _tokenize_keywords_en(text: str) -> set:
    if not text:
        return set()
    words = re.findall(r"[a-z][a-z0-9]*", text.lower())
    return {w for w in words if len(w) >= 2 and w not in _RANK_KEYWORD_STOPWORDS}


def _keyword_relevance_score(topic: str, doc: str) -> float:
    """Query-term recall on the document plus a small phrase-match bonus (English)."""
    tw = _tokenize_keywords_en(topic)
    if not tw:
        return 0.0
    dw = _tokenize_keywords_en(doc)
    if not dw:
        return 0.0
    overlap = len(tw & dw)
    recall = overlap / len(tw)
    denom = min(len(dw), max(len(tw) * 4, 12))
    density = overlap / denom if denom else 0.0
    score = 0.68 * recall + 0.32 * min(1.0, density)
    tl, dl = topic.lower().strip(), doc.lower()
    if len(tl) >= 10 and tl in dl:
        score = min(1.0, score + 0.14)
    elif overlap == len(tw) and len(tw) >= 2:
        score = min(1.0, score + 0.06)
    return round(min(1.0, score), 4)


def _result_document_text(r: dict) -> str:
    parts = [
        str(r.get("title") or ""),
        str(r.get("snippet") or ""),
        str(r.get("authors") or ""),
        str(r.get("venue") or ""),
    ]
    return " ".join(p for p in parts if p).strip()


def _bm25_tokenize(text: str) -> list:
    """Lowercase alphanumeric tokens for BM25 (and query)."""
    return re.findall(r"[a-z0-9]+", (text or "").lower()) or ["_"]


def _min_max_norm(vec: np.ndarray) -> np.ndarray:
    v = np.asarray(vec, dtype=np.float64)
    lo, hi = float(v.min()), float(v.max())
    if hi - lo < 1e-12:
        return np.ones_like(v) * 0.5
    return (v - lo) / (hi - lo)


def _scores_to_order(scores: np.ndarray) -> list:
    """Indices best-first (descending score)."""
    return [i for i, _ in sorted(enumerate(scores), key=lambda x: (-x[1], x[0]))]


def _rrf_fuse(orders: list, k: int) -> np.ndarray:
    """Reciprocal rank fusion over multiple best-first index lists."""
    n = max((max(o, default=-1) for o in orders), default=-1) + 1
    if n <= 0:
        return np.array([])
    acc = np.zeros(n, dtype=np.float64)
    for order in orders:
        for pos, doc_i in enumerate(order):
            acc[doc_i] += 1.0 / (k + pos + 1)
    return acc


def _get_bi_encoder():
    global _RANK_BI_ENCODER
    if _RANK_BI_ENCODER is None:
        from sentence_transformers import SentenceTransformer
        print(f"  🔄 Loading bi-encoder ({RANK_BI_ENCODER_MODEL_NAME})...")
        _RANK_BI_ENCODER = SentenceTransformer(RANK_BI_ENCODER_MODEL_NAME)
        print("  ✅ Bi-encoder ready")
    return _RANK_BI_ENCODER


def _get_cross_encoder():
    global _CROSS_ENCODER
    if _CROSS_ENCODER is None:
        from sentence_transformers import CrossEncoder
        print(f"  🔄 Loading cross-encoder ({RANK_CROSS_ENCODER_MODEL})...")
        _CROSS_ENCODER = CrossEncoder(RANK_CROSS_ENCODER_MODEL)
        print("  ✅ Cross-encoder ready")
    return _CROSS_ENCODER


def rank_by_relevance(topic: str, results: list) -> list:
    """
    Dense (BGE) + BM25 + keyword → RRF or normalized weighted sum → optional
    top-K cross-encoder rerank. Puts `raw_score` in [0,1] (min-max on fused scores).
    """
    if not results:
        return []

    topic_clean = (topic or "").strip()
    if not topic_clean:
        for r in results:
            r["raw_score"] = 0.0
            r["semantic_score"] = None
            r["keyword_score"] = 0.0
            r["bm25_score"] = None
            r["cross_encoder_score"] = None
        return results

    n = len(results)
    docs = [_result_document_text(r) for r in results]
    keyword_scores = np.array(
        [_keyword_relevance_score(topic_clean, d) for d in docs], dtype=np.float64
    )

    def _apply_keyword_only():
        for r, kw in zip(results, keyword_scores):
            r["semantic_score"] = None
            r["bm25_score"] = None
            r["keyword_score"] = round(float(kw), 4)
            r["cross_encoder_score"] = None
            r["raw_score"] = round(float(kw), 4)

    bm25_scores = np.zeros(n, dtype=np.float64)
    try:
        from rank_bm25 import BM25Okapi
        corpus_tokens = [_bm25_tokenize(d) for d in docs]
        bm25 = BM25Okapi(corpus_tokens)
        bm25_scores = np.array(
            bm25.get_scores(_bm25_tokenize(topic_clean)), dtype=np.float64
        )
    except ImportError:
        print("  ⚠️  rank-bm25 not installed → BM25 skipped in fusion")
    except Exception as e:
        print(f"  ⚠️  BM25 failed ({type(e).__name__}) → BM25 skipped")

    dense_scores = np.zeros(n, dtype=np.float64)
    try:
        from sentence_transformers import util
        model = _get_bi_encoder()
        q_text = BGE_QUERY_PREFIX + topic_clean
        topic_emb = model.encode(
            q_text,
            convert_to_tensor=True,
            normalize_embeddings=True,
        )
        texts = [d[:8192] if d else " " for d in docs]
        result_emb = model.encode(
            texts,
            convert_to_tensor=True,
            normalize_embeddings=True,
            show_progress_bar=False,
        )
        row = util.cos_sim(topic_emb, result_emb)[0]
        dense_scores = (
            row.detach().cpu().numpy()
            if hasattr(row, "detach")
            else np.asarray(row, dtype=np.float64)
        )
        dense_scores = np.clip(np.ravel(dense_scores), 0.0, 1.0)
    except ImportError:
        print("  ⚠️  sentence-transformers not installed → keyword-only ranking")
        _apply_keyword_only()
        return sorted(results, key=lambda r: r["raw_score"], reverse=True)
    except Exception as e:
        print(f"  ⚠️  Bi-encoder failed ({type(e).__name__}: {e}) → keyword-only")
        _apply_keyword_only()
        return sorted(results, key=lambda r: r["raw_score"], reverse=True)

    orders = [
        _scores_to_order(dense_scores),
        _scores_to_order(bm25_scores),
        _scores_to_order(keyword_scores),
    ]
    if RANK_MERGE_MODE == "rrf":
        fused = _rrf_fuse(orders, RRF_K)
    elif RANK_MERGE_MODE == "weighted_norm":
        nd = _min_max_norm(dense_scores)
        nb = _min_max_norm(bm25_scores)
        nk = np.clip(keyword_scores, 0.0, 1.0)
        fused = (
            _WEIGHTED_NORM_DENSE * nd
            + _WEIGHTED_NORM_BM25 * nb
            + _WEIGHTED_NORM_KEYWORD * nk
        )
    else:
        fused = _rrf_fuse(orders, RRF_K)

    # Optional cross-encoder on top-K by fused score
    prelim_order = _scores_to_order(fused)
    K = min(RANK_CROSS_ENCODER_TOP_K, n) if RANK_CROSS_ENCODER_TOP_K > 0 else 0
    ce_by_idx = {}
    if K > 0:
        try:
            ce = _get_cross_encoder()
            top_idx = prelim_order[:K]
            pairs = [
                (topic_clean, (docs[i] or " ")[:2000]) for i in top_idx
            ]
            ce_raw = np.array(
                ce.predict(pairs, show_progress_bar=False), dtype=np.float64
            )
            ce_n = _min_max_norm(ce_raw)
            fus_sub = np.array([fused[i] for i in top_idx], dtype=np.float64)
            fus_n = _min_max_norm(fus_sub)
            for j, idx in enumerate(top_idx):
                fused[idx] = float(
                    _CROSS_ENCODER_BLEND * ce_n[j]
                    + (1.0 - _CROSS_ENCODER_BLEND) * fus_n[j]
                )
                ce_by_idx[idx] = round(float(ce_raw[j]), 4)
            print(
                f"  ✅ Cross-encoder rerank applied to top {K} of {n} (blend={_CROSS_ENCODER_BLEND})"
            )
        except ImportError:
            print("  ⚠️  CrossEncoder unavailable → skipped rerank")
        except Exception as e:
            print(f"  ⚠️  Cross-encoder rerank skipped ({type(e).__name__}: {e})")

    fused_norm = _min_max_norm(fused)

    for i, r in enumerate(results):
        r["semantic_score"] = round(float(dense_scores[i]), 4)
        r["bm25_score"] = round(float(bm25_scores[i]), 4)
        r["keyword_score"] = round(float(keyword_scores[i]), 4)
        r["cross_encoder_score"] = ce_by_idx.get(i)
        r["raw_score"] = round(float(fused_norm[i]), 4)

    print(
        f"  ✅ Ranking: BGE dense + BM25 + keyword → {RANK_MERGE_MODE}"
        + (f" (RRF k={RRF_K})" if RANK_MERGE_MODE == "rrf" else "")
        + f" ({n} items)"
    )

    return sorted(results, key=lambda r: r["raw_score"], reverse=True)


print("✅ 의미론적 랭커 정의 완료")
print("   사용 가능한 함수: rank_by_relevance(topic, results)")

"""## 셀 4 — 신뢰도 평가 (Reliability Scorer)

각 결과에 0.0 ~ 1.0 점수를 매기고 🟢 신뢰 / 🟡 불확실 / 🔴 비신뢰 등급을 부여합니다.

### X / Threads 게시물의 특별 처리

X나 Threads 게시물은 게시물 자체(x.com)의 도메인이 아니라
**게시물 안에 링크된 논문/저널의 도메인**으로 신뢰도를 평가합니다.

```
X 게시물 → x.com          → 도메인 점수 낮음 (0.05)
               ↓ paper_url
           → nature.com   → 도메인 점수 높음 (0.40) ← 이걸 씁니다
```

nature.com을 링크한 트윗은 랜덤 X 게시물보다 훨씬 높은 신뢰도를 받습니다.

### 전체 채점 기준

| 항목 | 최대 점수 | 비고 |
|------|-----------|------|
| 도메인 권위 | 0.40 | X/Threads는 paper_url 도메인 기준 |
| 인용 수 | 0.20 | 500회 이상이면 만점 |
| 학술지/학회 명성 | 0.20 | NeurIPS, Nature, IEEE 등 |
| 콘텐츠 일관성 | 0.15 | 충분히 긴 설명, 이모지 남발 없음 |
| 부정 신호 패널티 | -0.40 | 음모론, 비속어 등 |

### 등급
🟢 **신뢰**: ≥ 0.70 &nbsp;|&nbsp; 🟡 **불확실**: 0.40–0.69 &nbsp;|&nbsp; 🔴 **비신뢰**: < 0.40

"""

import re
from urllib.parse import urlparse

RELIABLE_DOMAINS = {
    # Core academic repositories
    "nature.com", "science.org", "cell.com", "thelancet.com",
    "nejm.org", "bmj.com", "arxiv.org", "biorxiv.org", "medrxiv.org",
    "scholar.google.com", "semanticscholar.org", "pubmed.ncbi.nlm.nih.gov",
    "ieeexplore.ieee.org", "dl.acm.org", "openreview.net",
    "proceedings.mlr.press", "jmlr.org", "aaai.org",
    # Major academic publishers
    "sciencedirect.com", "springer.com", "springerlink.com",
    "wiley.com", "onlinelibrary.wiley.com",
    "jstor.org", "tandfonline.com", "sagepub.com",
    "oxfordacademic.com", "academic.oup.com",
    "cambridge.org", "press.princeton.edu",
    "plos.org", "plosone.org", "ploscompbiol.org", "plosmedicine.org",
    "frontiersin.org", "mdpi.com", "hindawi.com",
    "royalsocietypublishing.org", "pnas.org", "science.sciencemag.org",
    "jamanetwork.com", "acpjournals.org", "ahajournals.org",
    "diabetesjournals.org", "bloodjournal.org", "asnjournals.org",
    "researchgate.net", "academia.edu",
    # Preprint and open access
    "ssrn.com", "osf.io", "zenodo.org", "figshare.com",
    # University presses and repositories
    "mit.edu", "stanford.edu", "harvard.edu", "berkeley.edu",
    "caltech.edu", "cmu.edu", "ox.ac.uk", "cam.ac.uk",
}

# University domain pattern — any .edu or .ac.uk/.ac.jp etc.
_UNI_PATTERN = re.compile(r'\.(edu|ac\.[a-z]{2}|edu\.[a-z]{2})$')

RELIABLE_VENUES = {
    "neurips", "icml", "iclr", "cvpr", "acl", "emnlp",
    "nature", "science", "cell", "lancet", "nejm", "bmj", "ieee", "acm",
    "pnas", "plos", "jama", "aha", "annals",
}

UNRELIABLE_SIGNALS = [
    r"\b(conspiracy|fake|hoax|debunked|pseudoscience)\b",
    r"\b(lol|omg|wtf|bruh)\b",
    r"🔥{3,}",
]


def _domain_score(url: str) -> float:
    """Return the domain authority score (0–0.40) for a given URL."""
    try:
        domain = urlparse(url).netloc.replace("www.", "")
        if domain in RELIABLE_DOMAINS:      return 0.40
        if _UNI_PATTERN.search(domain):     return 0.38
        if domain.endswith(".gov"):         return 0.35
        if domain.endswith(".org"):         return 0.15
    except Exception:
        pass
    return 0.0


def score_reliability(result: dict) -> dict:
    """단일 결과에 신뢰도 점수와 등급을 부여합니다."""
    score     = 0.0
    url       = result.get("url", "")
    paper_url = result.get("paper_url", "")
    snippet   = result.get("snippet", "").lower()
    venue     = result.get("venue", "").lower()
    citations = result.get("citations", 0) or 0
    source    = result.get("source", "")

    # 1) 도메인 권위 (0 ~ 0.40)
    # For X and Threads: score the paper_url they link to, not the post URL.
    # A tweet linking to nature.com is far more credible than x.com itself.
    # Fall back to the post URL score if no paper_url.
    if source in ("x", "threads"):
        paper_score = _domain_score(paper_url) if paper_url else 0.0
        post_score  = 0.05   # base credit for being a social post
        score += max(paper_score, post_score)

        # Also check paper domain against venue list
        if paper_url:
            paper_domain = urlparse(paper_url).netloc.replace("www.", "").lower()
            for v in RELIABLE_VENUES:
                if v in paper_domain:
                    score += 0.20
                    break
    else:
        score += _domain_score(url)

    # 2) 인용 수 (0 ~ 0.20)
    if   citations >= 500: score += 0.20
    elif citations >= 100: score += 0.15
    elif citations >= 20:  score += 0.10
    elif citations >= 5:   score += 0.05

    # 3) 학술지/학회 명성 — from venue field (Scholar results)
    if source not in ("x", "threads"):
        for v in RELIABLE_VENUES:
            if v in venue:
                score += 0.20
                break

    # 4) 콘텐츠 일관성 (0 ~ 0.15)
    if   len(snippet) > 150: score += 0.10
    elif len(snippet) > 60:  score += 0.05
    if len(re.findall(r"[^\w\s,.]", snippet)) < 3:
        score += 0.05

    # 5) 부정 신호 패널티 (최대 -0.40)
    for pattern in UNRELIABLE_SIGNALS:
        if re.search(pattern, snippet, re.IGNORECASE):
            score -= 0.20

    # 6) 소스별 조정
    if source == "scholar":
        score = min(score + 0.10, 1.0)

    score = round(max(0.0, min(score, 1.0)), 3)

    result["reliability_score"] = score
    result["reliability_tier"]  = (
        "reliable"   if score >= 0.70 else
        "uncertain"  if score >= 0.40 else
        "unreliable"
    )
    return result


def score_all_reliability(results: dict) -> dict:
    """모든 소스의 결과에 신뢰도 점수를 적용합니다."""
    for source in ["scholar", "x", "threads"]:
        results[source] = [score_reliability(r) for r in results.get(source, [])]
    return results


print("✅ 신뢰도 평가기 정의 완료")
print("   사용 가능한 함수: score_reliability(result), score_all_reliability(results)")

"""## 셀 5 — 중복 제거 (Cross-Platform Deduplicator)

여러 플랫폼에서 같은 내용이 중복 수집되는 경우를 제거합니다.

예: 어떤 NeurIPS 논문이 Scholar에서도 뜨고 X에서도 누군가 공유했다면 하나만 남깁니다.

### 중복 판정 방법

**1단계 — URL 완전 일치**: 같은 URL이면 즉시 중복 처리

**2단계 — 제목 자카드 유사도**: 두 제목의 단어 집합이 75% 이상 겹치면 중복 처리
```
제목 A: {advances, in, llm, alignment}      (4 단어)
제목 B: {recent, advances, llm, alignment}  (4 단어)
공통:   {advances, llm, alignment}          → 3개
전체:   {advances, in, llm, alignment, recent} → 5개
자카드: 3/5 = 0.60  →  임계값 0.75 미만이므로 중복 아님
```

중복 발견 시 **신뢰도 점수가 더 높은 버전**을 남깁니다.

"""

def deduplicate(results: dict) -> dict:
    """
    Scholar / X / Threads 결과에서 중복을 제거합니다.
    중복 중 신뢰도 점수가 높은 것을 남깁니다.
    """
    all_items = [
        item
        for source in ["scholar", "x", "threads", "web"]
        for item in results.get(source, [])
    ]

    # 신뢰도가 높은 것이 먼저 처리되어 살아남도록 내림차순 정렬
    all_items.sort(key=lambda r: r.get("reliability_score", 0), reverse=True)

    seen_urls:   set  = set()
    seen_titles: list = []
    deduped:     list = []

    for item in all_items:
        url   = item.get("url", "")
        title = item.get("title", "").lower().strip()

        if url in seen_urls:
            continue

        if any(_jaccard(title, seen) > 0.75 for seen in seen_titles):
            continue

        deduped.append(item)
        seen_urls.add(url)
        seen_titles.append(title)

    removed = len(all_items) - len(deduped)
    if removed > 0:
        print(f"  🗑️  중복 {removed}개 제거")

    return {
        "scholar": [r for r in deduped if r["source"] == "scholar"],
        "x":       [r for r in deduped if r["source"] == "x"],
        "threads": [r for r in deduped if r["source"] == "threads"],
        "web":     [r for r in deduped if r["source"] == "web"],
    }


def _jaccard(a: str, b: str) -> float:
    """두 문자열의 단어 집합 간 자카드 유사도를 계산합니다."""
    sa, sb = set(a.split()), set(b.split())
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / len(sa | sb)


print("✅ 중복 제거기 정의 완료")
print("   사용 가능한 함수: deduplicate(results)")

"""## 셀 6 — 초록 요약 (Abstract Summarizer)

Scholar에서 가져온 긴 논문 초록을 2~3 문장으로 압축합니다.

### 사용 모델: `sshleifer/distilbart-cnn-12-6`
- **BART** 기반 요약 모델의 경량화(distilled) 버전
- 크기: 약 1.2GB — 파이프라인에서 가장 무거운 단계
- 뉴스 기사 요약용으로 훈련됐지만 학술 초록에도 잘 작동합니다

### GPU 자동 감지
Colab GPU 런타임이면 `cuda`, 아니면 `cpu`로 자동 전환합니다.

### Lazy Loading
모델을 처음 사용할 때 한 번만 로드하고 이후엔 메모리에 유지합니다.
처리 조건: Scholar 결과 중 300자 이상인 초록만 요약합니다.

"""

_summarizer_model = None


def _get_summarizer():
    """요약 모델을 처음 호출 시 로드하고 이후엔 재사용합니다 (lazy loading)."""
    global _summarizer_model
    if _summarizer_model is None:
        try:
            import torch
            from transformers import pipeline as hf_pipeline

            device = "cuda" if torch.cuda.is_available() else "cpu"
            print(f"  🔄 요약 모델 로딩 중 (sshleifer/distilbart-cnn-12-6) on {device}...")

            _summarizer_model = hf_pipeline(
                "summarization",
                model="sshleifer/distilbart-cnn-12-6",
                device=device,
            )
            print("  ✅ 요약 모델 로드 완료")
        except ImportError:
            print("  ⚠️  transformers 없음 → 요약 단계 건너뜀")
    return _summarizer_model


def summarize_abstracts(results: dict) -> dict:
    """
    300자 이상인 Scholar 초록을 2~3 문장으로 요약합니다.
    transformers 미설치 시 조용히 건너뜁니다.
    """
    candidates = [
        r for r in results.get("scholar", [])
        if len(r.get("snippet", "")) > 300
    ]

    if not candidates:
        return results

    summarizer = _get_summarizer()
    if summarizer is None:
        return results

    for item in candidates:
        try:
            output = summarizer(
                item["snippet"],
                max_length=80,
                min_length=30,
                do_sample=False,
            )
            item["snippet"] = output[0]["summary_text"]
        except Exception as e:
            print(f"  ⚠️  '{item.get('title','')}' 요약 실패 (원본 유지): {e}")

    print(f"  ✅ {len(candidates)}개 초록 요약 완료")
    return results


print("✅ 초록 요약기 정의 완료")
print("   사용 가능한 함수: summarize_abstracts(results)")

"""## 셀 7 — 캐시 (Semantic Cache)

검색 기록을 SQLite DB에 저장하고, 같은 주제를 다시 검색하면 마지막 검색 이후의 새 결과만 가져옵니다.

### SQLite 데이터베이스
모든 기록은 단일 파일 `research_cache.db` 에 저장됩니다. 서버 설치가 필요 없습니다.

### 의미론적 쿼리 매칭
단순 문자열 비교 대신 **의미가 같은 쿼리를 같은 것으로 인식**합니다.

```
"LLM alignment"          →  벡터 [0.82, 0.11, ...]
"대형 언어 모델 정렬"     →  벡터 [0.79, 0.13, ...]  유사도 0.91 → 캐시 히트!
"large language model safety" → 벡터 [0.77, 0.15, ...]  유사도 0.88 → 캐시 히트!
```

**모델: `paraphrase-multilingual-MiniLM-L12-v2`** — 50개 이상 언어 지원, 한국어↔영어 교차 매칭 가능

### 델타 페칭
캐시 히트 시 `last_run` 날짜를 스크래퍼에 전달해 그 이후 결과만 수집합니다.
새 결과는 `is_new=True`, 기존 결과는 `is_new=False` 로 표시됩니다.

"""

import sqlite3
import json
import numpy as np
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

DB_PATH = Path("/content/research_cache.db")
SIMILARITY_THRESHOLD = 0.82
_cache_embed_model = None


def _get_cache_embed_model():
    """다국어 임베딩 모델을 처음 호출 시 로드합니다."""
    global _cache_embed_model
    if _cache_embed_model is None:
        try:
            from sentence_transformers import SentenceTransformer
            print("  🔄 다국어 임베딩 모델 로딩 중 (paraphrase-multilingual-MiniLM-L12-v2)...")
            _cache_embed_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
            print("  ✅ 모델 로드 완료")
        except ImportError:
            print("  ⚠️  sentence-transformers 없음 → 정확한 문자열 매칭으로 대체")
    return _cache_embed_model


def _embed_query(text: str) -> Optional[np.ndarray]:
    m = _get_cache_embed_model()
    return m.encode(text, convert_to_numpy=True).astype(np.float32) if m else None


def _cosine(a: np.ndarray, b: np.ndarray) -> float:
    denom = np.linalg.norm(a) * np.linalg.norm(b)
    return float(np.dot(a, b) / denom) if denom else 0.0


def _get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


def _init_db():
    with _get_conn() as conn:
        conn.executescript(
            "CREATE TABLE IF NOT EXISTS queries ("
            "    id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "    topic TEXT NOT NULL UNIQUE,"
            "    embedding BLOB,"
            "    aliases TEXT DEFAULT '[]',"
            "    last_run TEXT NOT NULL,"
            "    run_count INTEGER DEFAULT 1,"
            "    created_at TEXT NOT NULL"
            ");"
            "CREATE TABLE IF NOT EXISTS results ("
            "    id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "    query_id INTEGER NOT NULL REFERENCES queries(id),"
            "    source TEXT NOT NULL,"
            "    title TEXT, authors TEXT, date TEXT, snippet TEXT, url TEXT,"
            "    citations INTEGER DEFAULT 0, venue TEXT,"
            "    raw_score REAL DEFAULT 0,"
            "    reliability_score REAL DEFAULT 0,"
            "    reliability_tier TEXT DEFAULT 'uncertain',"
            "    is_new INTEGER DEFAULT 1,"
            "    first_seen TEXT NOT NULL,"
            "    UNIQUE(query_id, url)"
            ");"
        )

_init_db()


def find_similar_query(topic: str) -> Optional[dict]:
    """의미론적으로 유사한 기존 쿼리를 찾습니다."""
    emb = _embed_query(topic)
    if emb is None:
        return _get_exact_query(topic)

    with _get_conn() as conn:
        rows = conn.execute(
            "SELECT id, topic, embedding, aliases, last_run, run_count "
            "FROM queries WHERE embedding IS NOT NULL"
        ).fetchall()

    if not rows:
        return None

    best_score, best_row = 0.0, None
    for row in rows:
        score = _cosine(emb, np.frombuffer(row["embedding"], dtype=np.float32))
        if score > best_score:
            best_score, best_row = score, row

    if best_score < SIMILARITY_THRESHOLD or not best_row:
        return None

    print(f"  💾 캐시 히트: '{topic}' ≈ '{best_row['topic']}' (유사도: {best_score:.3f})")

    aliases = json.loads(best_row["aliases"] or "[]")
    if topic not in aliases:
        aliases.append(topic)
        with _get_conn() as conn:
            conn.execute(
                "UPDATE queries SET aliases=? WHERE id=?",
                (json.dumps(aliases, ensure_ascii=False), best_row["id"])
            )

    return _load_query(best_row["id"])


def _get_exact_query(topic: str) -> Optional[dict]:
    with _get_conn() as conn:
        row = conn.execute("SELECT * FROM queries WHERE topic=?", (topic,)).fetchone()
        if not row:
            return None
        return _load_query(row["id"])


def _load_query(qid: int) -> dict:
    with _get_conn() as conn:
        row     = conn.execute("SELECT * FROM queries WHERE id=?", (qid,)).fetchone()
        results = conn.execute(
            "SELECT * FROM results WHERE query_id=? ORDER BY reliability_score DESC", (qid,)
        ).fetchall()
        return {
            "query_id":  row["id"],
            "topic":     row["topic"],
            "aliases":   json.loads(row["aliases"] or "[]"),
            "last_run":  row["last_run"],
            "run_count": row["run_count"],
            "results":   [dict(r) for r in results],
        }


def save_to_cache(topic: str, processed: dict, canonical_id: Optional[int] = None) -> int:
    """처리된 결과를 SQLite에 저장합니다."""
    now  = datetime.now(timezone.utc).isoformat()
    emb  = _embed_query(topic)
    blob = emb.tobytes() if emb is not None else None

    with _get_conn() as conn:
        if canonical_id:
            conn.execute(
                "UPDATE queries SET last_run=?, run_count=run_count+1 WHERE id=?",
                (now, canonical_id)
            )
            qid = canonical_id
        else:
            ex = conn.execute("SELECT id FROM queries WHERE topic=?", (topic,)).fetchone()
            if ex:
                conn.execute(
                    "UPDATE queries SET last_run=?, run_count=run_count+1, embedding=? WHERE id=?",
                    (now, blob, ex["id"])
                )
                qid = ex["id"]
            else:
                cur = conn.execute(
                    "INSERT INTO queries(topic, embedding, aliases, last_run, created_at) VALUES(?,?,?,?,?)",
                    (topic, blob, "[]", now, now)
                )
                qid = cur.lastrowid

        for source in ["scholar", "x", "threads", "web"]:
            for item in processed.get(source, []):
                conn.execute(
                    "INSERT INTO results"
                    "    (query_id,source,title,authors,date,snippet,url,citations,venue,"
                    "     raw_score,reliability_score,reliability_tier,is_new,first_seen)"
                    " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
                    " ON CONFLICT(query_id,url) DO UPDATE SET"
                    "    reliability_score=excluded.reliability_score,"
                    "    reliability_tier=excluded.reliability_tier,"
                    "    raw_score=excluded.raw_score, is_new=0",
                    (qid, item.get("source"), item.get("title"), item.get("authors"),
                     item.get("date"), item.get("snippet"), item.get("url"),
                     item.get("citations", 0), item.get("venue"),
                     item.get("raw_score", 0.0), item.get("reliability_score", 0.0),
                     item.get("reliability_tier", "uncertain"),
                     1 if item.get("is_new", True) else 0, now)
                )
        conn.commit()

    return qid


def get_search_history() -> list:
    """저장된 검색 기록을 반환합니다."""
    with _get_conn() as conn:
        rows = conn.execute(
            "SELECT q.id, q.topic, q.aliases, q.last_run, q.run_count, COUNT(r.id) AS result_count "
            "FROM queries q LEFT JOIN results r ON r.query_id=q.id "
            "GROUP BY q.id ORDER BY q.last_run DESC LIMIT 20"
        ).fetchall()
    return [{**dict(r), "aliases": json.loads(dict(r).get("aliases") or "[]")} for r in rows]


print("✅ 캐시 레이어 정의 완료")
print(f"   DB 위치: {DB_PATH}")
print("   사용 가능한 함수: find_similar_query(), save_to_cache(), get_search_history()")

"""## 셀 8 — 🚀 파이프라인 실행

지금까지 정의한 모든 단계를 순서대로 실행합니다. 각 플랫폼에서 상위 5개 결과를 반환합니다.

```
주제 입력 + 날짜 범위 선택
    ↓
1️⃣  캐시 확인 → 2️⃣  스크래핑 → 3️⃣  랭킹
    → 4️⃣  신뢰도 → 5️⃣  중복 제거 → 6️⃣  요약 → 7️⃣  저장
    ↓
결과 출력 (플랫폼별 소스 링크 포함)
```

**날짜 범위 선택 (Serper 지원 옵션과 정확히 일치):**
| 번호 | 의미 | Serper tbs |
|------|------|------------|
| 1 | 지난 1시간 | qdr:h |
| 2 | 지난 24시간 | qdr:d |
| 3 | 지난 1주일 | qdr:w |
| 4 | 지난 1개월 | qdr:m |
| 5 | 지난 1년 | qdr:y |
| 6 / Enter | 전체 기간 | (없음) |

"""

import asyncio
import re
from typing import Optional

TIER_ICON    = {"reliable": "🟢", "uncertain": "🟡", "unreliable": "🔴"}
TIER_KO      = {"reliable": "신뢰", "uncertain": "불확실", "unreliable": "비신뢰"}
SOURCE_LABEL = {"scholar": "Google Scholar", "x": "X / Twitter", "threads": "Threads", "web": "Web"}
SOURCE_BASE  = {"scholar": "https://scholar.google.com",
                "x":       "https://x.com",
                "threads": "https://www.threads.net",
                "web":     "https://google.com"}


# ── Date input parsing ────────────────────────────────────────────────────────

def parse_date_input(raw: str) -> Optional[int]:
    """
    Maps user selection to days. Options align exactly with Serper's tbs buckets:
      1 → past hour    (qdr:h — treated as 1 day for Scholar year filter)
      2 → past 24 hrs  (qdr:d)
      3 → past week    (qdr:w)
      4 → past month   (qdr:m)
      5 → past year    (qdr:y)
      6 / Enter → all time
    Returns None for all time, or a sentinel int that maps to the right tbs.
    """
    mapping = {"1": 0, "2": 1, "3": 7, "4": 30, "5": 365, "6": None}
    return mapping.get(raw.strip(), None)


def days_to_tbs_direct(days: Optional[int]) -> Optional[str]:
    """
    Direct mapping from our day sentinels to exact Serper tbs values.
    0  = past hour  → qdr:h
    1  = past day   → qdr:d
    7  = past week  → qdr:w
    30 = past month → qdr:m
    365= past year  → qdr:y
    None = all time → no tbs
    """
    if days is None:   return None
    if days == 0:      return "qdr:h"
    if days == 1:      return "qdr:d"
    if days == 7:      return "qdr:w"
    if days == 30:     return "qdr:m"
    if days == 365:    return "qdr:y"
    return None


def days_to_label(days: Optional[int]) -> str:
    labels = {0: "지난 1시간", 1: "지난 24시간", 7: "지난 1주일",
              30: "지난 1개월", 365: "지난 1년"}
    return labels.get(days, "전체 기간") if days is not None else "전체 기간"


# ── Result display ────────────────────────────────────────────────────────────

def print_results(topic: str, days: Optional[int], results: dict, meta: dict):
    total = sum(len(v) for v in results.values())
    new_  = sum(1 for v in results.values() for r in v if r.get("is_new"))

    print()
    print("=" * 65)
    print(f"  🔍 검색 주제: {topic}")
    print(f"  📅 날짜 필터: {days_to_label(days)}")
    if meta.get("is_cached"):
        print(f"  💾 캐시 히트 (마지막 검색: {meta['last_run'][:10]})")
    else:
        print(f"  ✨ 첫 검색 — 결과가 캐시에 저장됩니다")
    print(f"  📊 총 {total}개 결과 ({new_}개 신규)")
    print("=" * 65)

    for source in ["scholar", "x", "threads", "web"]:
        items = results.get(source, [])
        if not items:
            continue

        platform_url = SOURCE_BASE[source]
        print(f"\n── {SOURCE_LABEL[source]}  🔗 {platform_url}  ({len(items)}건) " + "─" * 10)

        for i, item in enumerate(items, 1):
            icon    = TIER_ICON.get(item["reliability_tier"], "⚪")
            tier    = TIER_KO.get(item["reliability_tier"], "")
            score   = int(item["reliability_score"] * 100)
            new_tag = "  [NEW]" if item.get("is_new") else ""

            print(f"\n  {i}. {item['title']}{new_tag}")
            sem_k = item.get("semantic_score")
            kw_k = item.get("keyword_score")
            bm_k = item.get("bm25_score")
            ce_k = item.get("cross_encoder_score")
            if sem_k is not None and kw_k is not None and bm_k is not None:
                detail = (
                    f"dense {float(sem_k):.2f}, BM25 {float(bm_k):.2f}, kw {float(kw_k):.2f}"
                )
                if ce_k is not None:
                    detail += f", CE {float(ce_k):.2f}"
                print(
                    f"     {icon} {tier} ({score}%)  |  relevance: {item['raw_score']:.2f} "
                    f"({detail})  |  {item['date']}"
                )
            else:
                print(f"     {icon} {tier} ({score}%)  |  relevance: {item['raw_score']:.2f}  |  {item['date']}")

            if item.get("authors"):
                print(f"     저자: {item['authors']}")
            if item.get("venue"):
                print(f"     게재: {item['venue']}")
            if item.get("citations"):
                print(f"     인용: {item['citations']:,}회")

            snippet = item.get("snippet", "")
            if snippet:
                words, line, lines = snippet.split(), "", []
                for w in words:
                    if len(line) + len(w) + 1 > 68:
                        lines.append(line); line = w
                    else:
                        line = f"{line} {w}".strip()
                if line:
                    lines.append(line)
                for ln in lines:
                    print(f"     {ln}")

            # X and Threads: show both the post and the paper it links to
            if source in ("x", "threads") and item.get("paper_url"):
                print(f"     📄 논문/기사: {item['paper_url']}")
                print(f"     📱 게시물:   {item['url']}")
            else:
                print(f"     🔗 {item['url']}")

    print()
    print("─" * 65)
    history = get_search_history()
    if history:
        print("  📋 검색 기록:")
        for h in history[:5]:
            aliases_str = ""
            if h["aliases"]:
                aliases_str = f"  (별칭: {', '.join(h['aliases'][:2])})"
            print(f"  • {h['topic']}  ({h['result_count']}건, {h['run_count']}회){aliases_str}")
    print("=" * 65)


# ── Pipeline ──────────────────────────────────────────────────────────────────

async def run_pipeline(topic: str, days: Optional[int] = None):
    print(f"\n🚀 파이프라인 시작: '{topic}'  ({days_to_label(days)})")
    print()

    print("1️⃣  캐시 확인 중...")
    cached       = find_similar_query(topic)
    canonical_id = cached["query_id"] if cached else None
    since_date   = cached["last_run"] if (cached and not days) else None
    if not cached:
        print("   캐시 없음 — 전체 수집 시작")
    elif days:
        print(f"   캐시 있음 — 날짜 필터({days_to_label(days)}) 우선 적용")
    else:
        print(f"   캐시 히트 — 마지막 검색({cached['last_run'][:10]}) 이후 결과만 가져옵니다")

    print("\n2️⃣  데이터 수집 중 (Scholar + X + Threads 동시)...")
    raw    = await scrape_all(topic, days=days)
    counts = {k: len(v) for k, v in raw.items()}
    parts  = []
    for src, label in [("scholar","Scholar"),("x","X"),("threads","Threads"),("web","Web")]:
        n = counts[src]
        parts.append(f"{label} {n}건" if n else f"{label} —")
    print(f"   수집 완료: {' / '.join(parts)}")

    if not any(counts.values()):
        print("   ⚠️  모든 소스에서 결과를 찾지 못했습니다. 주제를 바꿔 다시 시도해보세요.")
        return

    print("\n3️⃣  의미론적 랭킹 중...")
    all_flat = [item for src in ["scholar", "x", "threads", "web"] for item in raw.get(src, [])]
    ranked   = rank_by_relevance(topic, all_flat)
    split = {
        "scholar": [r for r in ranked if r["source"] == "scholar"],
        "x":       [r for r in ranked if r["source"] == "x"],
        "threads": [r for r in ranked if r["source"] == "threads"],
        "web":     [r for r in ranked if r["source"] == "web"],
    }

    print("\n4️⃣  신뢰도 평가 중...")
    split = score_all_reliability(split)
    tiers = {"reliable": 0, "uncertain": 0, "unreliable": 0}
    for items in split.values():
        for item in items:
            tiers[item["reliability_tier"]] += 1
    print(f"   🟢 신뢰 {tiers['reliable']}건  🟡 불확실 {tiers['uncertain']}건  🔴 비신뢰 {tiers['unreliable']}건")

    print("\n5️⃣  중복 제거 중...")
    split = deduplicate(split)

    print("\n6️⃣  긴 초록 요약 중...")
    split = summarize_abstracts(split)

    if cached:
        seen_urls = {r["url"] for r in cached["results"]}
        for src in ["scholar", "x", "threads", "web"]:
            for item in split.get(src, []):
                item["is_new"] = item["url"] not in seen_urls

    print("\n7️⃣  캐시 저장 중...")
    qid = save_to_cache(topic, split, canonical_id=canonical_id)
    print(f"   저장 완료 (query_id={qid})")

    meta = {"is_cached": bool(cached), "last_run": cached["last_run"] if cached else None}
    print_results(topic, days, split, meta)


# ── User input ────────────────────────────────────────────────────────────────

print()
topic = input("🔍 검색 주제를 입력하세요 (한국어 가능): ").strip()

if not topic:
    print("주제를 입력하지 않았습니다.")
else:
    print()
    print("📅 날짜 범위를 선택하세요:")
    print("   1. 지난 1시간")
    print("   2. 지난 24시간")
    print("   3. 지난 1주일")
    print("   4. 지난 1개월")
    print("   5. 지난 1년")
    print("   6. 전체 기간 (기본값)")
    raw_date = input("   번호 입력 (Enter = 전체 기간): ").strip()
    days     = parse_date_input(raw_date)

    if raw_date and raw_date not in ("1","2","3","4","5","6",""):
        print(f"   ⚠️  '{raw_date}' 인식 불가 — 전체 기간으로 검색합니다")

    await run_pipeline(topic, days=days)